name: jenkins-trigger

on:
  pull_request:
    branches: [ main ]
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'deploy')
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull request
        run: ${{ secrets.UPLOAD_PLAY_STORE }}
