name: jenkins-trigger

on:
  pull_request:
    branches: [ main ]
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull request
        run: curl -X POST 'http://woozoora:112cb53528846bfdb54f8a3b8dc9165407@3.36.8.193:9090/job/woozoora-uploader/build?token=generateBundle'
